name: Testing Math Operation Functions

on: 
  push:
    branches: ["main"]

  pull_request:
    types: [opened, edited]
    branches: ["main"]

  workflow_dispatch:

env:
  TEST_FILE: sum

# Jobs are separated to view the use of dependencies cache
jobs:
  test-sum:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      
      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deps-node-modules-${{hashFiles('**/package-lock.json')}}

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        id: sum_test
        run: npm test $TEST_FILE

        #failure() indicates that this step will evaluate on failure
      - name: Failed test
        if: failure() && steps.sum_test.outcome == 'failure'
        run: echo 'Test for sum operation failed!'

  test-subtract:
    #Indicates that the jobs needs to wait for the execution of 'Test_Math_Operation' to end
    needs: [test-sum]
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      
      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deps-node-modules-${{hashFiles('**/package-lock.json')}}

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test subtract 

  test-exponents:
    needs: [test-sum, test-subtract]
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      
      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deps-node-modules-${{hashFiles('**/package-lock.json')}}

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test exponent 
