#Matrixes allows the workflow to run for each value in the matrix

name: Matrix Demo
on: workflow_dispatch
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        node-version: [12, 14, 16]
        operating-system: [ubuntu-latest, windows-latest]
      #includes a especific combination to the matrix
      include:
        - node-version: 18
          operation-system: ubuntu-latest
          
      #removes a especific combination to the matrix
      exclude:
        - node-version: 12
          operation-system: windows-latest

    #This job will run once for each value in operating-system
    runs-on: ${{matrix.operating-system}}
    steps:
      - name: Get Code
        uses: actions/checkout@v4

      #This job will run once for each value in node-version
      - name: Intall NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}

      - name: Install Dependencies
        run: npm ci

      - name: Build project
        run: echo "Build completed!"