name: Output information

on: 
  workflow_dispatch:

jobs:
  info:
    #NOTE: on windows-latest the echo command works different and need to change the sintaxis to send athe output
    runs-on: ubuntu-latest
    outputs:
      github-context: ${{steps.context.outputs.github-context}}
    steps:
      - name: Output GitHub context
        id: context
        run: echo "github-context=Hello" >> "$GITHUB_OUTPUT"
  print:
    runs-on: ubuntu-latest
    needs: info
    steps:
      - name: Output Contex
        run: echo "${{needs.info.outputs.github-context}}"
