name: Use Reusable workflow
on: workflow_dispatch
jobs:
  test-sum:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      
      - name: Cache Dependencies
        uses: actions/cache@v4

        with:
          path: ~/.npm
          key: deps-node-modules-${{hashFiles('**/package-lock.json')}}

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        id: sum_test
        run: npm test sum

  Build:
    needs: test-sum
    uses: ./.github/workflows/reusable.yml
    with:
      message: "Deployed"
